name: Deploy to Azure

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: download code
      uses: actions/checkout@v4
    
    - name: download Node.jobs
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: download dependences
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: run unit tests
      run: npm run test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: download code (checkout)
      uses: actions/checkout@v4
    
    - name: Login on Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Config Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build and send (push)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/alerta-cidadao-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Conect by SSH and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: azureuser
        key: ${{ secrets.SSH_KEY }}
        port: 22
        sync: true
        debug: true
        script: |
          cd /home/azureuser || exit

          echo "download new image..."
          sudo docker compose pull api

          echo "updating container..."
          sudo docker compose up -d --no-deps api

          echo "Cleaning disc"
          sudo docker image prune -f